# This is a configuration file for setting up python graphs
# This will be loaded to plot.py when it starts running
--- # document start

## General Variables  ###########################################

func: "plt_lambda_loss_excel" # Inspect PlotGraphs for available functions
no_channels: 1 # number of channels
normalise: true # normalise data

files: 
  "./results/moscap/dc_tests.xlsx": # path/to/file
    - "dev2"

#################################################################   

## Plot Variables ###############################################
title: ""
xlabel: "Length [mm]"
ylabel: "Normalised Loss [dB]"
end_of_legend: "mm" # legend = {length}{end_of_legend}

x_range:
  start: 1553
  stop: 1554

save: true # if true, it will save the image to the specified filepath
save_fpath: "./Si loss.png"
#################################################################


# Filtering signal parameters - moving average ##################
signal_filter: false # require filtering the signal?
window_size: 100
#################################################################


## Length Loss Plots Only Variables #####################################
exp_lambda: 1550 # wavelength of interest [nm]
lambda_avgrange: 1 # wavelength range for averaging data points [nm] e.g. 10: x-5 to x+5
columns_drop:
  "./results/Chip_3/Si_iloss_data.xlsx": # path/to/file
    "Si Waveguide":
      - 4
      - 16
  "./results/Chip_6/KTN_chip.xlsx":
    "Si waveguide":
      - 24
  "./results/Chip_9/result.xlsx":
    "Si waveguide":
      - 24
#################################################################


## Wavelength Loss Plots Only Variables #################################
# if nothing is specified then it will plot all data ####################
columns_plot:
  "./results/moscap/dc_tests.xlsx": # path/to/file
    "dev2":
      - -4
      - 0
      - 4

    

#################################################################


## DC Loss Plots Only Variables #################################
dc_drop:
#################################################################
... # document end